FROM todo.microservice.local:base AS dev

WORKDIR /app

RUN apt-get update \
    && apt-get install -y unzip \
    && mkdir -p /vsdbg \
    && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

WORKDIR /src
COPY src .

WORKDIR /src/API
RUN dotnet restore

EXPOSE 8080

CMD ["dotnet", "watch", "run", "--no-launch-profile", "--urls=http://0.0.0.0:8080"]