apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth.fullname" . }}
  labels:
    app: {{ include "auth.name" . }}
    chart: {{ include "auth.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "auth.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "auth.name" . }}
    spec:
      containers:
        - name: {{ include "auth.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName }}
            - secretRef:
                name: {{ .Values.secretName }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}